# Data warehouse compose
version: '3.8'

services:
  clickhouse-server:
    image: clickhouse/clickhouse-server:24.3.13.40
    container_name: log-clickhouse-server
    environment:
      - CLICKHOUSE_INIT_TIMEOUT=60
      # clickhouse data permission
      - CLICKHOUSE_UID=101
      - CLICKHOUSE_GID=101
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      # auto seed clickhouse with required db and table data
      - ./sample_data/:/etc/sample_data/
      - ./migrations/1_init.sql:/docker-entrypoint-initdb.d/1_init.sql
    ports:
      - "8123:8123"
      - "9001:9001"
    networks:
      - grafana_grafana-net
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8123/ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    cap_add:
      - SYS_NICE
      - NET_ADMIN
      - IPC_LOCK
      - SYS_PTRACE

networks:
  grafana_grafana-net:
    external: true
