# Data warehouse compose
version: '3.8'

services:
  clickhouse-server:
    image: clickhouse/clickhouse-server:24.3.13.40
    container_name: log-clickhouse-server
    environment:
      - CLICKHOUSE_INIT_TIMEOUT=60
      # clickhouse data permission
      - CLICKHOUSE_UID=101
      - CLICKHOUSE_GID=101
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - ./volumes/data-log:/var/lib/clickhouse
      - ./volumes/logs-log:/var/log/clickhouse-server
      # auto seed clickhouse with required db and table
      - ./migrations/1_init.sql:/docker-entrypoint-initdb.d/1_init.sql
    ports:
      - "8123:8123"
      - "9000:9000"
    networks:
      - wh-net
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8123/ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    user: "${UID:-$(id -u)}:${GID:-$(id -g)}"
    cap_add:
      - SYS_NICE
      - NET_ADMIN
      - IPC_LOCK
      - SYS_PTRACE

networks:
  wh-net:
    driver: bridge
  
