version: '3.8'

services:
  clickhouse-server:
    image: clickhouse/clickhouse-server:24.3.13.40-alpine
    # image: yandex/clickhouse-server:21.3.20.1
    container_name: log-clickhouse-server
    environment:
      - CLICKHOUSE_INIT_TIMEOUT=60
      # clickhouse data permission
      - CLICKHOUSE_UID=101
      - CLICKHOUSE_GID=101
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      # - ./volumes/data-log:/var/lib/clickhouse
      - ./volumes/logs-log:/var/log/clickhouse-server
      # auto seed clickhouse with required db and table
      - ./migrations/1_init.sql:/docker-entrypoint-initdb.d/1_init.sql
    ports:
      - "8123:8123"
      - "9000:9000"
    networks:
      - log-net
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8123/ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    user: "${UID:-101}:${GID:-101}"
    cap_add:
      - SYS_NICE
      - NET_ADMIN
      - IPC_LOCK
      - SYS_PTRACE

  vector:
    depends_on:
      clickhouse-server:
        condition: service_healthy
    image: timberio/vector:0.42.0-alpine
    container_name: log-vector
    volumes:
      - ./vector.yaml:/etc/vector/vector.yaml:ro
      # mount log file paths as necessary with :ro read only permissions
      - ../data/stream/logs:/var/log/data/stream:ro
      - ../data/processing/logs:/var/log/data/processing:ro
    env_file:
      - .env
    ports:  
      - "8686:8686"
    networks:
      - log-net
  
networks:
  log-net:
    external: true
    name: grafana_log-net
  
