name: Kafka Consumer & Model Processing

on:
  pull_request:
    types:
      - closed
  push:
    branches:
      - main
      # - ci-cd
    
jobs:
  deployment:
    name: Service Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install SSH client
        run: sudo apt-get install openssh-client

      - name: Export SSH key
        run: echo "${{ secrets.SSH_KEY }}" > ssh-key.pem

      - name: Update SSH key permissions
        run: chmod 400 ssh-key.pem

      # TODO: remove checkout to ci-cd
      - name: Connect to VM & Deploy services
        run: |
          ssh -o StrictHostKeyChecking=no -i ssh-key.pem ${{ secrets.PRODUCER_INSTANCE_USERNAME }}@${{ secrets.PROC_INSTANCE_HOST }} << 'EOF'
          [ -d "$(pwd)/ericsson" ] && rm -rf ericsson || true &&
          git clone git@github.com:rayhanrandi/ericsson.git || true &&
          cd ./ericsson || true && 
          cd ./data/PROCESSING || true &&
          echo LOG_LEVEL=${{ secrets.PRODUCER_LOG_LEVEL }} > .env || true &&
          echo KAFKA_BROKER=${{ secrets.PRODUCER_KAFKA_BROKER }} >> .env || true &&
          echo KAFKA_TOPIC=${{ secrets.PRODUCER_KAFKA_TOPIC }} >> .env || true &&
          echo KAFKA_CONSUMER_GROUP=${{ secrets.CONSUMER_KAFKA_CONSUMER_GROUP }} >> .env || true &&
          echo VECTOR_AGGREGATOR_SINK_ADDR=${{ secrets.VECTOR_AGGREGATOR_SINK_ADDR }} >> .env || true &&
          echo CLICKHOUSE_HOST=${{ secrets.RAG_CLICKHOUSE_HOST }} >> .env || true &&
          echo CLICKHOUSE_PORT=${{ secrets.RAG_CLICKHOUSE_PORT }} >> .env || true &&
          echo CLICKHOUSE_USERNAME=${{ secrets.RAG_CLICKHOUSE_USERNAME }} >> .env || true &&
          echo CLICKHOUSE_DATABASE=${{ secrets.RAG_CLICKHOUSE_DATABASE }} >> .env || true &&
          echo CLICKHOUSE_SENSOR_TABLE=${{ secrets.CONSUMER_CLICKHOUSE_SENSOR_TABLE }}
          cd ../.. || true &&
          make proc-down || true && make proc-up || true
          EOF
    

