name: Service Deployment

on:
  pull_request:
    types:
      - closed
  push:
    branches:
      - main
    #   - ci-cd

jobs:
  deployment:
    name: Kafka
    runs-on: ubuntu-latest
    steps:
      - name: Template
        run: echo "Template"
    