name: Data Lake (Clickhouse OLAP1)

on:
  pull_request:
    branches:
      - main
    types:
      - closed
  push:
    branches:
      - main
      - ci-cd
  
jobs:
  deployment:
    name: Service Deployment 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install SSH client
        run: sudo apt-get install openssh-client

      - name: Export SSH key
        run: echo "${{ secrets.SSH_KEY }}" > ssh-key.pem

      - name: Update SSH key permissions
        run: chmod 400 ssh-key.pem

      # TODO: remove checkout to ci-cd
      # backs up existing data volume and redeploys clickhouse
      - name: Connect to VM & Deploy services
        run: |
          ssh -o StrictHostKeyChecking=no -i ssh-key.pem ${{ secrets.LAKE_INSTANCE_USERNAME }}@${{ secrets.LAKE_INSTANCE_HOST }} << 'EOF'
          [ -d "$(pwd)/ericsson/data/volumes/" ] && cp -r ~/ericsson/data/volumes/ ~/ || true &&
          sudo rm -rf ericsson || true &&
          git clone git@github.com:rayhanrandi/ericsson.git || true &&
          cd ./ericsson || true && git checkout ci-cd || true &&
          cp -r ~/volumes/ ./data || true &&    
          make lake-down || true && make lake-up || true
          EOF

    