name: LLM RAG

on:
  pull_request:
    types:
      - closed
  push:
    branches:
      - main
      - ci-cd
    
jobs:
  deployment:
    name: Service Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install SSH client
        run: sudo apt-get install openssh-client

      - name: Export SSH key
        run: echo "${{ secrets.SSH_KEY }}" > ssh-key.pem

      - name: Update SSH key permissions
        run: chmod 400 ssh-key.pem

      # TODO: remove checkout to ci-cd
      - name: Connect to VM & Deploy services
        run: |
          ssh -o StrictHostKeyChecking=no -i ssh-key.pem ${{ secrets.PRODUCER_INSTANCE_USERNAME }}@${{ secrets.PRODUCER_INSTANCE_HOST }} << 'EOF'
          [ -d "$(pwd)/ericsson" ] && rm -rf ericsson || true &&
          git clone git@github.com:rayhanrandi/ericsson.git || true &&
          cd ./ericsson || true && git checkout ci-cd || true &&
          cd ./rag || true &&
          echo LOG_LEVEL=${{ secrets.RAG_LOG_LEVEL }} > .env || true &&
          echo DATA_INTERVAL=${{ secrets.RAG_DATA_INTERVAL }} >> .env || true &&
          echo CRON_SLICES=${{ secrets.RAG_CRON_SLICES }} >> .env || true &&
          echo TOGETHER_ENDPOINT=${{ secrets.RAG_TOGETHER_ENDPOINT }} >> .env || true &&
          echo TOGETHER_API_KEY=${{ secrets.RAG_TOGETHER_API_KEY }} >> .env || true &&
          echo TOGETHER_LLM_MODEL=${{ secrets.RAG_TOGETHER_LLM_MODEL }} >> .env || true &&
          echo CLICKHOUSE_HOST=${{ secrets.RAG_CLICKHOUSE_HOST }} >> .env || true &&
          echo CLICKHOUSE_PORT=${{ secrets.RAG_CLICKHOUSE_PORT }} >> .env || true &&
          echo CLICKHOUSE_USERNAME=${{ secrets.RAG_CLICKHOUSE_USERNAME }} >> .env || true &&
          echo CLICKHOUSE_DATABASE=${{ secrets.RAG_CLICKHOUSE_DATABASE }} >> .env || true &&
          echo CLICKHOUSE_ANALYSIS_TABLE=${{ secrets.RAG_CLICKHOUSE_ANALYSIS_TABLE }} >> .env || true &&
          echo CLICKHOUSE_SUMMARY_TABLE=${{ secrets.RAG_CLICKHOUSE_SUMMARY_TABLE }} >> .env || true &&
          echo VECTOR_AGGREGATOR_SINK_ADDR=${{ secrets.VECTOR_AGGREGATOR_SINK_ADDR }} >> .env || true &&
          cd ../.. || true &&
          make llm-down || true && make llm-up || true
          EOF