name: Service Deployment - Spark

on:
  pull_request:
    types:
      - closed
  push:
    branches:
      - main
    #   - ci-cd
    
jobs:
  deployment:
    name: Template
    runs-on: ubuntu-latest
    steps:
      - name: Template
        run: echo "Template"
    
