name: Service Deployment - Vector Aggregator, Grafana

on:
  pull_request:
    types:
      - closed
  push:
    branches:
      - main
      - ci-cd
  
jobs:
  deployment:
    name: Vector Aggregator, Grafana
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install SSH client
        run: sudo apt-get install openssh-client

      - name: Export SSH key
        run: echo "${{ secrets.SSH_KEY }}" > ssh-key.pem

      - name: Update SSH key permissions
        run: chmod 400 ssh-key.pem

      # TODO: remove checkout to ci-cd
      - name: Connect to VM & Deploy services
        run: |
          ssh -o StrictHostKeyChecking=no -i ssh-key.pem ${{ secrets.LOG_INSTANCE_USERNAME }}@${{ secrets.LOG_INSTANCE_HOST }} << 'EOF'
          rm -rf ericsson || true &&
          git clone git@github.com:rayhanrandi/ericsson.git || true &&
          cd ./ericsson || true && git checkout ci-cd || true &&
          cd ./grafana || true &&
          echo CLICKHOUSE_HOST=${{ secrets.WH_CLICKHOUSE_HOST }} > .env || true &&
          echo CLICKHOUSE_DB=${{ secrets.WH_CLICKHOUSE_DB }} >> .env || true &&
          echo CLICKHOUSE_TABLE=${{ secrets.WH_CLICKHOUSE_TABLE }} >> .env || true &&
          cd .. || true &&
          make grafana-up
          EOF
